import { chromium } from '@playwright/test';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--no-sandbox','--use-gl=swiftshader','--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1440, height: 940 } });
await p.goto('http://127.0.0.1:4173/');
await p.waitForFunction(() => window.__gcars?.debug().ready === true, null, { timeout: 60000 });
await p.click('#speeds button:last-child');
await p.waitForTimeout(30000);
await p.locator('.archive-panel').scrollIntoViewIfNeeded();
await p.waitForTimeout(600);
await p.screenshot({ path: '/tmp/ui-archive.png' });
await p.locator('.chart-panel').scrollIntoViewIfNeeded();
await p.waitForTimeout(600);
await p.screenshot({ path: '/tmp/ui-side.png' });
await b.close();
const m = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--no-sandbox','--use-gl=swiftshader','--enable-unsafe-swiftshader'] });
const mp = await m.newPage({ viewport: { width: 393, height: 852 }, hasTouch: true, isMobile: true });
await mp.goto('http://127.0.0.1:4173/');
await mp.waitForFunction(() => window.__gcars?.debug().ready === true, null, { timeout: 60000 });
await mp.waitForTimeout(12000);
await mp.screenshot({ path: '/tmp/ui-mob1.png' });
await mp.locator('.archive-panel').scrollIntoViewIfNeeded();
await mp.waitForTimeout(400);
await mp.screenshot({ path: '/tmp/ui-mob2.png' });
await m.close();
